
namespace SubCentral.GUI {
    public enum GUIControls {
        SEARCHBUTTON = 201,
        CANCELBUTTON = 202,
        LANGUAGESBUTTON = 203,
        MODIFYSEARCHBUTTON = 204,
        SORTBUTTON = 205,

        PROVIDERSLIST = 50,

        MODIFYSEARCHOKBUTTON = 211,
        MODIFYSEARCHCANCELBUTTON = 212,
        MODIFYSEARCHREVERTBUTTON = 213,
        MODIFYSEARCHCLEARFILESBUTTON = 214,
        MODIFYSEARCHSELECTFOLDERBUTTON = 215,
        MODIFYSEARCHMOVIEBUTTON = 216,
        MODIFYSEARCHTVSHOWBUTTON = 217,
        MODIFYSEARCHIMDBIDBUTTON = 221,
        MODIFYSEARCHTITLEBUTTON = 222,
        MODIFYSEARCHYEARBUTTON = 223,
        MODIFYSEARCHSEASONBUTTON = 224,
        MODIFYSEARCHEPISODEBUTTON = 225,

        DUMMYMAINVIEW = 101,
        DUMMYSEARCHVIEW = 102,
        DUMMYMODIFYSEARCH = 103
    }
}